baseURL = "https://learn-scopes.westerbly.dev/"
languageCode = "en-us"
title = "Programming in Scopes"
theme = "book"
enableGitInfo = true

[params]
BookTheme = "light"
BookRepo = "https://github.com/radgeRayden/scopes-tutorial"
BookSection = "*"
